/**
 * The single source of truth for which operations the public API exposes.
 *
 * Three documents describe the same surface and must never disagree:
 * `public/openapi.json` (generated by `scripts/build-openapi.mjs`),
 * `/api/index.json` (the runtime index) and the `/developers` portal table.
 * They all key off the `operationId`s below, and a unit test asserts the list
 * matches the generated OpenAPI document.
 */

export const API_ENDPOINTS = [
  { operationId: 'getApiIndex', pathTemplate: '/api/index.json' },
  { operationId: 'listPosts', pathTemplate: '/api/posts.json' },
  { operationId: 'listPostsInEnglish', pathTemplate: '/api/posts-en.json' },
  { operationId: 'listPostsInSpanish', pathTemplate: '/api/posts-es.json' },
  { operationId: 'listSeries', pathTemplate: '/api/series/{lang}/index.json' },
  { operationId: 'getSeries', pathTemplate: '/api/series/{lang}/{slug}.json' },
  {
    operationId: 'getTimelineByTag',
    pathTemplate: '/api/timeline/{lang}/{tag}.json',
  },
  {
    operationId: 'getSlidesTimeline',
    pathTemplate: '/api/slides-timeline/{lang}.json',
  },
] as const;

export type ApiOperationId = (typeof API_ENDPOINTS)[number]['operationId'];

export function pathTemplateFor(operationId: ApiOperationId): string {
  const endpoint = API_ENDPOINTS.find(
    (candidate) => candidate.operationId === operationId
  );
  if (!endpoint) {
    throw new Error(`Unknown API operationId: ${operationId}`);
  }
  return endpoint.pathTemplate;
}
