import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

/**
 * Structural guards for `public/openapi.json`.
 *
 * The spec is generated by `scripts/build-openapi.mjs`; these tests pin the
 * properties agents and scanners actually depend on — an `operationId` and a
 * typed response schema on every operation (function-calling compatibility),
 * a documented error model on every operation, and paths that match the files
 * the build really emits.
 */

const ROOT = process.cwd();
const spec = JSON.parse(
  readFileSync(resolve(ROOT, 'public/openapi.json'), 'utf8')
);

const operations = Object.entries(
  spec.paths as Record<string, Record<string, Record<string, unknown>>>
).flatMap(([path, item]) =>
  Object.entries(item).map(([method, operation]) => ({
    path,
    method,
    operation,
  }))
);

describe('OpenAPI document', () => {
  it('is OpenAPI 3.1 and names the product in the title', () => {
    expect(spec.openapi).toBe('3.1.0');
    expect(spec.info.title).toContain('XergioAleX.com');
  });

  it('declares contact, license and external documentation', () => {
    expect(spec.info.contact?.url).toBeTruthy();
    expect(spec.info.license?.name).toBeTruthy();
    expect(spec.externalDocs?.url).toBe('https://xergioalex.com/developers');
  });

  it('states that no authentication is required', () => {
    expect(spec.security).toEqual([]);
    expect(spec.info.description).toMatch(/## Authentication/);
  });

  it('documents the versioning policy', () => {
    expect(spec.info.version).toMatch(/^\d+\.\d+\.\d+$/);
    expect(spec.info.description).toMatch(/## Versioning and deprecation/);
    expect(spec.info.description).toContain('/api/v2/');
    expect(spec.info.description).toContain('X-API-Version');
    expect(spec.info.description).toContain('Sunset');
  });

  it('documents the rate-limit policy and its response headers', () => {
    expect(spec.info.description).toMatch(/## Methods and rate limits/);
    expect(spec.info.description).toContain('RateLimit-Policy');
    expect(spec.info.description).toContain('Retry-After');
    for (const header of [
      'XApiVersion',
      'RateLimitPolicy',
      'RateLimit',
      'RateLimitLimit',
      'RateLimitRemaining',
      'RateLimitReset',
      'RetryAfter',
      'Deprecation',
      'Sunset',
    ]) {
      expect(
        spec.components.headers[header],
        `${header} component`
      ).toBeTruthy();
    }
  });

  it('exposes at least one operation', () => {
    expect(operations.length).toBeGreaterThan(0);
  });
});

describe('every operation', () => {
  it('has a unique operationId', () => {
    const ids = operations.map(({ operation }) => operation.operationId);
    for (const id of ids) {
      expect(typeof id).toBe('string');
      expect(id).not.toBe('');
    }
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('has a summary, a description and a tag', () => {
    for (const { path, operation } of operations) {
      expect(operation.summary, `summary of ${path}`).toBeTruthy();
      expect(operation.description, `description of ${path}`).toBeTruthy();
      expect(operation.tags, `tags of ${path}`).toBeTruthy();
    }
  });

  it('returns a typed 200 schema with a concrete example and standard headers', () => {
    for (const { path, operation } of operations) {
      const ok = (operation.responses as any)?.['200'];
      const schema = ok?.content?.['application/json']?.schema;
      expect(schema, `200 schema of ${path}`).toBeTruthy();
      // A $ref into components — never an untyped `{ type: 'object' }`.
      expect(schema.$ref, `200 schema of ${path} must be a $ref`).toMatch(
        /^#\/components\/schemas\//
      );
      // A concrete sample value: what makes the operation usable as an
      // LLM tool description without fetching it first.
      expect(
        ok.content['application/json'].examples?.default?.value,
        `200 example of ${path}`
      ).toBeTruthy();
      // The version / rate-limit / deprecation headers every response carries.
      expect(ok.headers?.['X-API-Version']?.$ref, `headers of ${path}`).toBe(
        '#/components/headers/XApiVersion'
      );
      expect(ok.headers?.['RateLimit-Policy']?.$ref).toBe(
        '#/components/headers/RateLimitPolicy'
      );
    }
  });

  it('documents the shared error model on 404, 429 and 500', () => {
    for (const { path, operation } of operations) {
      const responses = operation.responses as Record<string, any>;
      expect(responses['404']?.$ref, `404 of ${path}`).toBe(
        '#/components/responses/NotFound'
      );
      expect(responses['429']?.$ref, `429 of ${path}`).toBe(
        '#/components/responses/TooManyRequests'
      );
      expect(responses['500']?.$ref, `500 of ${path}`).toBe(
        '#/components/responses/InternalError'
      );
    }
  });

  it('types and describes every path parameter', () => {
    for (const { path, operation } of operations) {
      const templated = path.match(/\{([^}]+)\}/g) ?? [];
      const parameters = (operation.parameters as any[]) ?? [];
      expect(parameters.length, `parameters of ${path}`).toBe(templated.length);
      for (const parameter of parameters) {
        expect(parameter.description, `${path} ${parameter.name}`).toBeTruthy();
        expect(parameter.schema?.type, `${path} ${parameter.name}`).toBe(
          'string'
        );
        expect(parameter.required).toBe(true);
      }
    }
  });
});

describe('error schema', () => {
  const error = spec.components.schemas.Error;

  it('carries both RFC 9457 members and the agent-facing error object', () => {
    expect(error.required).toEqual(
      expect.arrayContaining([
        'type',
        'title',
        'status',
        'detail',
        'instance',
        'error',
      ])
    );
    expect(error.properties.error.required).toEqual([
      'code',
      'message',
      'hint',
      'documentation_url',
    ]);
  });

  it('enumerates the same codes the edge middleware emits', () => {
    expect(error.properties.error.properties.code.enum).toEqual([
      'resource_not_found',
      'method_not_allowed',
      'gone',
      'rate_limited',
      'internal_error',
    ]);
  });

  it('serves errors as RFC 9457 application/problem+json', () => {
    for (const name of ['NotFound', 'TooManyRequests', 'InternalError']) {
      const response = (spec.components.responses as any)[name];
      expect(
        response.content['application/problem+json'],
        `${name} problem+json content`
      ).toBeTruthy();
      expect(response.content['application/problem+json'].schema.$ref).toBe(
        '#/components/schemas/Error'
      );
    }
    const tooManyRequests = (spec.components.responses as any).TooManyRequests;
    expect(tooManyRequests.headers['Retry-After'].$ref).toBe(
      '#/components/headers/RetryAfter'
    );
  });
});

describe('cross-document consistency', () => {
  it('the shared endpoint list matches the generated spec exactly', async () => {
    const { API_ENDPOINTS } = await import('@/lib/api-endpoints');

    const fromSpec = operations
      .map(({ path, operation }) => `${operation.operationId} ${path}`)
      .sort();
    const fromList = API_ENDPOINTS.map(
      (endpoint) => `${endpoint.operationId} ${endpoint.pathTemplate}`
    ).sort();

    expect(fromList).toEqual(fromSpec);
  });

  it('every operation has a description in both locales', async () => {
    const { API_ENDPOINTS } = await import('@/lib/api-endpoints');
    const { en } = await import('@/lib/translations/en');
    const { es } = await import('@/lib/translations/es');

    for (const { operationId } of API_ENDPOINTS) {
      expect(
        en.developersPage.endpoints.descriptions[operationId],
        `EN description for ${operationId}`
      ).toBeTruthy();
      expect(
        es.developersPage.endpoints.descriptions[operationId],
        `ES description for ${operationId}`
      ).toBeTruthy();
    }
  });
});

describe('paths', () => {
  it('resolve to real built files, not directory-style guesses', () => {
    // `/api/series/{lang}` would 404 — the build emits `index.json`.
    for (const { path } of operations) {
      expect(path, `${path} must name a .json file`).toMatch(/\.json$/);
    }
  });

  it('every $ref resolves', () => {
    const document = JSON.stringify(spec);
    const refs = new Set(
      Array.from(document.matchAll(/"\$ref":"(#\/[^"]+)"/g)).map((m) => m[1])
    );
    for (const ref of refs) {
      const target = ref
        .slice(2)
        .split('/')
        .reduce<any>((node, key) => node?.[key], spec);
      expect(target, `unresolved $ref ${ref}`).toBeTruthy();
    }
  });
});
